name: Docker Image CI

on:
  push:
  pull_request:
    paths-ignore:
    - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: dotnet/nbgv@v0.4.0
      id: nbgv
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
